//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nfu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nfu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AboutIcon {
            get {
                object obj = ResourceManager.GetObject("AboutIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFU is already running. Please close the other instance of NFU..
        /// </summary>
        internal static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFU Already Running.
        /// </summary>
        internal static string AlreadyRunningTitle {
            get {
                return ResourceManager.GetString("AlreadyRunningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFU.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;hangelog.
        /// </summary>
        internal static string ButtonChangeLog {
            get {
                return ResourceManager.GetString("ButtonChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co&amp;ntributors.
        /// </summary>
        internal static string ButtonContributors {
            get {
                return ResourceManager.GetString("ButtonContributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File(s).
        /// </summary>
        internal static string ButtonFiles {
            get {
                return ResourceManager.GetString("ButtonFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Import.
        /// </summary>
        internal static string ButtonImport {
            get {
                return ResourceManager.GetString("ButtonImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Issues.
        /// </summary>
        internal static string ButtonIssues {
            get {
                return ResourceManager.GetString("ButtonIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;License.
        /// </summary>
        internal static string ButtonLicense {
            get {
                return ResourceManager.GetString("ButtonLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open log.
        /// </summary>
        internal static string ButtonOpenLog {
            get {
                return ResourceManager.GetString("ButtonOpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Screenshot.
        /// </summary>
        internal static string ButtonScreenShot {
            get {
                return ResourceManager.GetString("ButtonScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Update.
        /// </summary>
        internal static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot handle clipboard content of type(s) {0}.
        /// </summary>
        internal static string CannotHandleContentTypes {
            get {
                return ResourceManager.GetString("CannotHandleContentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Naxiz/NFU/commits/master.
        /// </summary>
        internal static string ChangeLogUrl {
            get {
                return ResourceManager.GetString("ChangeLogUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        internal static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIFS.
        /// </summary>
        internal static string Cifs {
            get {
                return ResourceManager.GetString("Cifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Naxiz/NFU/graphs/contributors.
        /// </summary>
        internal static string ContributorsUrl {
            get {
                return ResourceManager.GetString("ContributorsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X: {0} Y: {1} W: {2} H: {3}
        ///{4}.
        /// </summary>
        internal static string CoordinatesOverlay {
            get {
                return ResourceManager.GetString("CoordinatesOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Louis Matthijssen 2014.
        /// </summary>
        internal static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter: {0}.
        /// </summary>
        internal static string Counter {
            get {
                return ResourceManager.GetString("Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        internal static string Decrypt {
            get {
                return ResourceManager.GetString("Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t delete {0}..
        /// </summary>
        internal static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable debug.
        /// </summary>
        internal static string DisableDebug {
            get {
                return ResourceManager.GetString("DisableDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some settings may only take effect after a restart.
        /// </summary>
        internal static string EffectAfterRestart {
            get {
                return ResourceManager.GetString("EffectAfterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable debug.
        /// </summary>
        internal static string EnableDebug {
            get {
                return ResourceManager.GetString("EnableDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable WebHook.
        /// </summary>
        internal static string EnableWebHook {
            get {
                return ResourceManager.GetString("EnableWebHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        internal static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExitIcon {
            get {
                object obj = ResourceManager.GetObject("ExitIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occured. NFU will exit..
        /// </summary>
        internal static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFU error.
        /// </summary>
        internal static string FatalErrorTitle {
            get {
                return ResourceManager.GetString("FatalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one or more files to upload.
        /// </summary>
        internal static string FilesTitle {
            get {
                return ResourceManager.GetString("FilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP.
        /// </summary>
        internal static string Ftp {
            get {
                return ResourceManager.GetString("Ftp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTPS (Explicit).
        /// </summary>
        internal static string FtpsExplicit {
            get {
                return ResourceManager.GetString("FtpsExplicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use generated filename.
        /// </summary>
        internal static string GeneratedFileName {
            get {
                return ResourceManager.GetString("GeneratedFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle the Pause key.
        /// </summary>
        internal static string HandlePauseKey {
            get {
                return ResourceManager.GetString("HandlePauseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle the Print Screen key.
        /// </summary>
        internal static string HandlePrintScreenKey {
            get {
                return ResourceManager.GetString("HandlePrintScreenKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host (FQDN).
        /// </summary>
        internal static string HostFqdn {
            get {
                return ResourceManager.GetString("HostFqdn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host in FQDN format.
        /// </summary>
        internal static string HostFqdnFormat {
            get {
                return ResourceManager.GetString("HostFqdnFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example.com.
        /// </summary>
        internal static string HostFqdnFormatExample {
            get {
                return ResourceManager.GetString("HostFqdnFormatExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hotkey could not be registered. Is it already in use?.
        /// </summary>
        internal static string HotKeyNotRegistered {
            get {
                return ResourceManager.GetString("HotKeyNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register hotkey.
        /// </summary>
        internal static string HotKeyNotRegisteredTitle {
            get {
                return ResourceManager.GetString("HotKeyNotRegisteredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESC - Cancel, ENTER - Confirm, F - Fullscreen, C - Toggle controls, Hold CTRL - To clipboard.
        /// </summary>
        internal static string HotKeysOverlay {
            get {
                return ResourceManager.GetString("HotKeysOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IcoMoon.
        /// </summary>
        internal static string IcoMoonName {
            get {
                return ResourceManager.GetString("IcoMoonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://icomoon.io.
        /// </summary>
        internal static string IcoMoonUrl {
            get {
                return ResourceManager.GetString("IcoMoonUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All icons.
        /// </summary>
        internal static string IcoMoonUsedFor {
            get {
                return ResourceManager.GetString("IcoMoonUsedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Naxiz/NFU/issues.
        /// </summary>
        internal static string IssuesUrl {
            get {
                return ResourceManager.GetString("IssuesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key path.
        /// </summary>
        internal static string KeyPath {
            get {
                return ResourceManager.GetString("KeyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have the latest version of NFU.
        /// </summary>
        internal static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Naxiz/NFU/blob/master/LICENSE.
        /// </summary>
        internal static string LicenseUrl {
            get {
                return ResourceManager.GetString("LicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, but the log isn&apos;t writeable. Debug mode will be disabled.
        ///
        ///Try to enable debug mode in order to solve this issue..
        /// </summary>
        internal static string LogNotWriteable {
            get {
                return ResourceManager.GetString("LogNotWriteable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge screens.
        /// </summary>
        internal static string MergeScreens {
            get {
                return ResourceManager.GetString("MergeScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to system tray.
        /// </summary>
        internal static string MinimizeToSystemTray {
            get {
                return ResourceManager.GetString("MinimizeToSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of NFU is available.
        /// </summary>
        internal static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NfuIcon {
            get {
                object obj = ResourceManager.GetObject("NfuIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files selected.
        /// </summary>
        internal static string NoFilesSelected {
            get {
                return ResourceManager.GetString("NoFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunKey doesn&apos;t exist..
        /// </summary>
        internal static string NoRunKey {
            get {
                return ResourceManager.GetString("NoRunKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use original filename.
        /// </summary>
        internal static string OriginalFileName {
            get {
                return ResourceManager.GetString("OriginalFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick screenshots.
        /// </summary>
        internal static string QuickScreenShots {
            get {
                return ResourceManager.GetString("QuickScreenShots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.RegisterHotKey.
        /// </summary>
        internal static string RegisterHotKey {
            get {
                return ResourceManager.GetString("RegisterHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterHotKey failed for key {0}.
        /// </summary>
        internal static string RegisterHotKeyFailed {
            get {
                return ResourceManager.GetString("RegisterHotKeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reupload screenshot.
        /// </summary>
        internal static string ReUploadScreenShot {
            get {
                return ResourceManager.GetString("ReUploadScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change RunKey..
        /// </summary>
        internal static string RunKeyChangeFailed {
            get {
                return ResourceManager.GetString("RunKeyChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen {0}.
        /// </summary>
        internal static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        internal static string ScreenShot {
            get {
                return ResourceManager.GetString("ScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The screenshot has been copied to the clipboard..
        /// </summary>
        internal static string ScreenShotCopied {
            get {
                return ResourceManager.GetString("ScreenShotCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFU screenshot copied.
        /// </summary>
        internal static string ScreenShotCopiedTitle {
            get {
                return ResourceManager.GetString("ScreenShotCopiedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret (optional).
        /// </summary>
        internal static string Secret {
            get {
                return ResourceManager.GetString("Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending WebHook payload....
        /// </summary>
        internal static string SendingWebHook {
            get {
                return ResourceManager.GetString("SendingWebHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute path for SFTP, relative path for FTP and CIFS.
        /// </summary>
        internal static string ServerDirectory {
            get {
                return ResourceManager.GetString("ServerDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /home/example.com/files (absolute) example.com/files (relative).
        /// </summary>
        internal static string ServerDirectoryExample {
            get {
                return ResourceManager.GetString("ServerDirectoryExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute path to the public SSH Key (OpenSSH format).
        /// </summary>
        internal static string ServerKey {
            get {
                return ResourceManager.GetString("ServerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\SSH\Keys\id_rsa.
        /// </summary>
        internal static string ServerKeyExample {
            get {
                return ResourceManager.GetString("ServerKeyExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for the server, empty for anonymous.
        /// </summary>
        internal static string ServerPassword {
            get {
                return ResourceManager.GetString("ServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example123!.
        /// </summary>
        internal static string ServerPasswordExample {
            get {
                return ResourceManager.GetString("ServerPasswordExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public URL pointing to your upload folder.
        /// </summary>
        internal static string ServerPublicUrl {
            get {
                return ResourceManager.GetString("ServerPublicUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://example.com/files/.
        /// </summary>
        internal static string ServerPublicUrlExample {
            get {
                return ResourceManager.GetString("ServerPublicUrlExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username for the server, empty for anonymous.
        /// </summary>
        internal static string ServerUserName {
            get {
                return ResourceManager.GetString("ServerUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to root.
        /// </summary>
        internal static string ServerUserNameExample {
            get {
                return ResourceManager.GetString("ServerUserNameExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings gone?.
        /// </summary>
        internal static string SettingsGone {
            get {
                return ResourceManager.GetString("SettingsGone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Naxiz/NFU/wiki/Upgrading#201412272.
        /// </summary>
        internal static string SettingsGoneUrl {
            get {
                return ResourceManager.GetString("SettingsGoneUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SettingsIcon {
            get {
                object obj = ResourceManager.GetObject("SettingsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFTP.
        /// </summary>
        internal static string Sftp {
            get {
                return ResourceManager.GetString("Sftp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFTP (SSH Keys).
        /// </summary>
        internal static string SftpSshKeys {
            get {
                return ResourceManager.GetString("SftpSshKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        internal static string ShowPassword {
            get {
                return ResourceManager.GetString("ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source on GitHub.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Naxiz/NFU.
        /// </summary>
        internal static string SourceUrl {
            get {
                return ResourceManager.GetString("SourceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFU relies on the SSH.NET library for SFTP uploads.
        ///Please download the DLL in the same directory as the NFU executable.
        ///The download link can be found in the about box..
        /// </summary>
        internal static string SshNetMissing {
            get {
                return ResourceManager.GetString("SshNetMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing DLL.
        /// </summary>
        internal static string SshNetMissingTitle {
            get {
                return ResourceManager.GetString("SshNetMissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH.NET.
        /// </summary>
        internal static string SshNetName {
            get {
                return ResourceManager.GetString("SshNetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sshnet.codeplex.com.
        /// </summary>
        internal static string SshNetUrl {
            get {
                return ResourceManager.GetString("SshNetUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFTP uploads.
        /// </summary>
        internal static string SshNetUsedFor {
            get {
                return ResourceManager.GetString("SshNetUsedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        internal static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on this icon to open NFU or right click to exit..
        /// </summary>
        internal static string StillActive {
            get {
                return ResourceManager.GetString("StillActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFU is still active.
        /// </summary>
        internal static string StillActiveTitle {
            get {
                return ResourceManager.GetString("StillActiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFU was unable to create a temporary file. Your temporary folder is probably full.
        ///
        ///Please clear your temporary folder and try again, or click cancel to cancel the upload (try {0} out of {1})..
        /// </summary>
        internal static string TemporaryFolderFull {
            get {
                return ResourceManager.GetString("TemporaryFolderFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary folder full.
        /// </summary>
        internal static string TemporaryFolderFullTitle {
            get {
                return ResourceManager.GetString("TemporaryFolderFullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFU uses the following third party resources (double click to visit).
        /// </summary>
        internal static string ThirdPartyResources {
            get {
                return ResourceManager.GetString("ThirdPartyResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadFile.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported data on clipboard..
        /// </summary>
        internal static string UnsupportedData {
            get {
                return ResourceManager.GetString("UnsupportedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untrusted certificate!
        ///
        ///Subject:
        ///{0}
        ///
        ///Issuer:
        ///{1}
        ///
        ///Hash:
        ///{2}
        ///
        ///Continue?.
        /// </summary>
        internal static string UntrustedCertificate {
            get {
                return ResourceManager.GetString("UntrustedCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untrusted certificate.
        /// </summary>
        internal static string UntrustedCertificateTitle {
            get {
                return ResourceManager.GetString("UntrustedCertificateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an update available for NFU..
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFU update available.
        /// </summary>
        internal static string UpdateAvailableTitle {
            get {
                return ResourceManager.GetString("UpdateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Check.
        /// </summary>
        internal static string UpdateCheck {
            get {
                return ResourceManager.GetString("UpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update has failed..
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFU UPDATE.
        /// </summary>
        internal static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating NFU....
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file failed to upload..
        /// </summary>
        internal static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFU upload failed.
        /// </summary>
        internal static string UploadFailedTitle {
            get {
                return ResourceManager.GetString("UploadFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading... ({0}/{1}).
        /// </summary>
        internal static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been successfully uploaded..
        /// </summary>
        internal static string UploadSuccessful {
            get {
                return ResourceManager.GetString("UploadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload successful.
        /// </summary>
        internal static string UploadSuccessfulStatus {
            get {
                return ResourceManager.GetString("UploadSuccessfulStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload successful.
        /// </summary>
        internal static string UploadSuccessfulTitle {
            get {
                return ResourceManager.GetString("UploadSuccessfulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used for.
        /// </summary>
        internal static string UsedFor {
            get {
                return ResourceManager.GetString("UsedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for NFU to exit....
        /// </summary>
        internal static string WaitingToExit {
            get {
                return ResourceManager.GetString("WaitingToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebHook.
        /// </summary>
        internal static string WebHook {
            get {
                return ResourceManager.GetString("WebHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (WebHook failed).
        /// </summary>
        internal static string WebHookFailed {
            get {
                return ResourceManager.GetString("WebHookFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipping directory....
        /// </summary>
        internal static string ZippingDirectory {
            get {
                return ResourceManager.GetString("ZippingDirectory", resourceCulture);
            }
        }
    }
}
